version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  checkout:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: mvn -version
      - run: mvn dependency:go-offline
      - run: mvn test

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload