version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn dependency:go-offline
            - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master