version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  checkout:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: mvn -version
      - run: mvn test
      - run: mvn site
      - run: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target


  upload-codecov:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: mvn test
      - run: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target
      - codecov/upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
  upload:
    jobs:
      - checkout
      - upload-codecov