version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  checkout:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      - checkout

  build:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn -version
            - run: mvn dependency:go-offline
            - run: mvn test
      - codecov/upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master