version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  checkout:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: mvn -version
      - run: mvn test
  upload:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
      - upload:
          requires:
            - checkout
            - build
          filters:
            branches:
              only:
                - master